# Generated by Django 5.2.5 on 2025-08-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='superuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
