# Generated by Django 5.2.5 on 2025-08-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MRP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
