# Generated by Django 5.2.5 on 2025-08-31 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
