# Generated by Django 5.2.5 on 2025-08-31 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
