# Generated by Django 5.2.5 on 2025-09-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='main.customer'),
        ),
    ]
