# Generated by Django 5.2.5 on 2025-09-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_route_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='customer',
        ),
    ]
