# Generated by Django 5.2.5 on 2025-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('order', 'Order')], default='order', max_length=20),
        ),
    ]
