# Generated by Django 5.2.5 on 2025-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('store', 'Store'), ('order', 'Order')], default='order', max_length=20),
        ),
    ]
