# Generated by Django 5.2.5 on 2025-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('order', 'Order')], max_length=20),
        ),
    ]
