# Generated by Django 5.2.5 on 2025-09-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_customernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernotification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
